package model.enums;

public enum TokenType {

	// KEYWORDS
    ABSTRACT, ASSERT, BOOLEAN, BREAK, BYTE,
    CASE, CATCH, CHAR, CLASS, CONST,
    CONTINUE, DEFAULT, DO, DOUBLE, ELSE,
    ENUM, EXTENDS, FINAL, FINALLY, FLOAT,
    FOR, GOTO, IF, IMPLEMENTS, IMPORT,
    INSTANCEOF, INT, INTERFACE, LONG, NATIVE,
    NEW, PACKAGE, PRIVATE, PROTECTED, PUBLIC,
    RETURN, SHORT, STATIC, STRICTFP, SUPER,
    SWITCH, SYNCHRONIZED, THIS, THROW, THROWS,
    TRANSIENT, TRY, VOID, VOLATILE, WHILE,

    // KEYWORDS (java moderno)
    VAR, YIELD, RECORD, SEALED, PERMITS, NON_SEALED,


    // IDENTIFIERS
    IDENTIFIER,

    // LITERALS
    INTEGER_LITERAL,
    FLOAT_LITERAL,
    BOOLEAN_LITERAL,
    CHAR_LITERAL,
    STRING_LITERAL,
    NULL_LITERAL,

    // OPERATORS

    // Aritméticos
    PLUS, MINUS, MULTIPLY, DIVIDE, MOD,

    // Incremento / Decremento
    INCREMENT, DECREMENT,

    // Atribuição
    ASSIGN,
    PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN,
    AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN,
    LEFT_SHIFT_ASSIGN, RIGHT_SHIFT_ASSIGN, UNSIGNED_RIGHT_SHIFT_ASSIGN,

    // Relacionais
    EQUAL, NOT_EQUAL,
    GREATER, LESS, GREATER_EQUAL, LESS_EQUAL,

    // Lógicos
    LOGICAL_AND, LOGICAL_OR, LOGICAL_NOT,

    // Bitwise
    BITWISE_AND, BITWISE_OR, BITWISE_XOR, BITWISE_NOT,

    // Shift
    LEFT_SHIFT, RIGHT_SHIFT, UNSIGNED_RIGHT_SHIFT,

    // Ternário
    QUESTION, COLON,

    // Outros
    INSTANCEOF_OPERATOR,

    // SEPARATORS
    LPAREN, RPAREN,           // ( )
    LBRACE, RBRACE,           // { }
    LBRACKET, RBRACKET,       // [ ]
    SEMICOLON,                // ;
    COMMA,                    // ,
    DOT,                      // .
    ELLIPSIS,                 // ...
    AT,                       // @
    DOUBLE_COLON,             // ::

    // COMMENTS
    LINE_COMMENT,
    BLOCK_COMMENT,
    DOC_COMMENT,

    // SPECIAL
    WHITESPACE,
    UNKNOWN,
    EOF
}
